export const dom = {
  unitDropDown: document.querySelector(".drop-down-cont"),
  unitButton: document.querySelector(".unit-button"),
  tempCels: document.querySelector(".temp-cels"),
  tempFah: document.querySelector(".temp-fah"),
  speedKm: document.querySelector(".speed-km"),
  speedM: document.querySelector(".speed-m"),
  precipMil: document.querySelector(".precip-mil"),
  precipInch: document.querySelector(".precip-inch"),
  searchInput: document.querySelector(".search-input"),
  submitSearch: document.querySelector(".submit-search"),
  country: document.querySelector(".country"),
  section1: document.querySelector(".section1"),
  firstResult: document.querySelector(".first-result"),
  hourlyGrid: document.querySelector(".hourly-grid"),
  hourlyDay: document.querySelector(".hourly-day-days"),
  selectedCont: document.querySelector(".selected-container"),
  units: document.querySelector(".units"),
  secondDropDown: document.querySelectorAll(".hourly-day-days li"),
  selectedDay: document.querySelector(".selected-day p"),
  // secondDropDown: document.querySelector(".selected-container"),
  // secondDropDown: document.querySelector(".selected-container"),
};
